spring:
  datasource:
    url: jdbc:mysql://203.195.246.36:3306/himoko?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
    username: root
    password: Aa123456
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
#     driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ucar.springbootdemo.pojo
  hikari:
    connection-timeout: 60000
server:
  port: 8089
